### ISSUE TITLE
Player does not always sit in the UFO

### ISSUE THREAD

**Issue by MrRar** [TerraQuest-Studios/ufo_ship#4]
It is caused by 3D Armor.

Even without 3D Armor sitting is unreliable. It is a Minetest bug. I fixed it in the Automobiles pack: https://github.com/APercy/automobiles_pck/commit/2e49602b19caceed6d8f02c5e14ea2922ce20384

![player_sit](https://user-images.githubusercontent.com/16406771/210864169-1ffef284-208a-4def-ad4e-963c22cd304b.PNG)

**Comment by wsor4035** [comment]
sorry, i really should have turned notifications on for this repo. known issue, just havent had a chance to dig into it yet
